name: Publish KB to gh-pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Build _site from HTML/HighLevel Branded
        run: |
          set -e
          mkdir -p _site
          cp -r "HTML/HighLevel Branded"/* _site/ || true
          # Stop Jekyll from processing
          touch _site/.nojekyll

          # If no index exists, create a simple landing page with links
          if [ ! -f "_site/index.html" ] && [ ! -f "_site/Index.html" ]; then
            echo '<!doctype html><meta charset="utf-8"><title>Knowledge Base</title><h1>Knowledge Base</h1><p>Select a category:</p><ul>' > _site/index.html
            # List top-level folders and make links (URL-encode names via python one-liner)
            for d in $(find _site -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | sort); do
              enc=$(python3 -c "import urllib.parse,sys; print(urllib.parse.quote(sys.argv[1]))" "$d")
              echo "<li><a href=\"${enc}/\">${d}</a></li>" >> _site/index.html
            done
            echo '</ul>' >> _site/index.html
          fi

          echo "---- PUBLISHING THESE FILES ----"
          ls -la _site
          echo "--------------------------------"

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: _site
          force_orphan: true
